name: Django CI

on:
  push:
    branches: [ main ]    # Cambia a 'master' si tu rama principal se llama así
  pull_request:
    branches: [ main ]    # Cambia a 'master' si es necesario

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Instala geckodriver para Firefox y xvfb para simular un entorno gráfico
          sudo apt-get install -y firefox-geckodriver xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in headless mode
        env:
          DISPLAY: :99.0
        run: |
          xvfb-run python manage.py test
